### ISSUE TITLE
Snippet Creation Method?

### ISSUE THREAD

**Issue by austin-guevara** [drewkinney/bootstrap-dreamweaver-snippets#2]
Hi there! Did you create these snippets manually (by going into Dreamweaver and creating them one at a time) or do you have some kind of automated process?

Thank you!

**Comment by drewkinney** [comment]
I extracted them by hand, to help myself with rapid prototyping.

**Comment by austin-guevara** [comment]
@drewkinney – thanks for responding! I've been trying to figure out if there‘s some script to generate Dreamweaver snippets, but it appears I may have to make one myself or just do things manually. Cheers!
